version: "3"

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
    - 8090:8080
    - 50000:50000
    volumes:
    - ./stable-jenkins_data:/var/jenkins_home
  
  jenkins-agent:
    image: jenkins/ssh-slave
    volumes:
    - ./stable-jenkins_data:/var/jenkins_home
    ports:
    - 0.0.0.0:30022:22
    environment:
      JENKINS_SLAVE_SSH_PUBKEY: ""

